### ISSUE TITLE
Compilation failure in Core Device info.cpp

### ISSUE THREAD

**Issue by harryhaaren** [gnu-guitar/gnu-guitar#1]
Hi,

Just done a git clone then ran git submodule init recursive, after which `mkdir build && cd build && cmake .. && make` and I get the following compile error:

```
In file included from /root/programming/gnu-guitar/components/core/include/gnu-guitar-core/busy-device.hpp:22:0,
                 from /root/programming/gnu-guitar/components/core/lib/busy-device.cpp:19:
/root/programming/gnu-guitar/components/core/include/gnu-guitar-core/error.hpp:25:20: error: expected ‘{’ before ‘::’ token
 namespace GnuGuitar::Core {
```

**Comment by tay10r** [comment]
The c++ compiler has to support nested namespaces. Try updating your compiler to a newer version.

**Comment by harryhaaren** [comment]
It looks like splitting the namespace lines would allow backwards compatibility with older compilers.. is that something you'd accept a PR for?

```
namespace GnuGuitar::Core {
```
becomes
```
namespace GnuGuitar {
namespace Core {
```
and the closing of the namespaces is similar?

**Comment by harryhaaren** [comment]
For reference, I'm on gcc 5.2.1 and clang 3.6.1, neither of which support nested namespaces.

**Comment by tay10r** [comment]
@harryhaaren I would accept a PR for it.

That would be a whole lot of work though! Just know that there are files that do not use nested namespaces and are formatted like this:

```
namespace GnuGuitar {

namespace Core {

/* class declarations */

} // namespace Core

} // namespace GnuGuitar
```

Notice the space between the namespaces.

If you think it looks better without the space, that's okay too - just remove the space from the files that have it. I care more about the consistency.

However, if you want to avoid all that work, you can install the latest version of GCC and Clang. If you're distro doesn't support it, each of them have PPAs you can add.

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt install gcc
```

And LLVM has debian packages available [here](http://apt.llvm.org/).

**Comment by harryhaaren** [comment]
Sure, upgrading toolchain is probably the easiest solution/workaround for now. Thanks for the replies, I'll close this now.
