### ISSUE TITLE
Compilation: missing file

### ISSUE THREAD

**Issue by ycollet** [gnu-guitar/gnu-guitar#2]
A CMakeLists.txt file is missing in gnu-guitar/components/gui/external/qaccordion/
This directory is totally empty.

**Comment by tay10r** [comment]
Did you get any errors downloading the submodules recursively?

**Comment by tay10r** [comment]
What is the output of `git submodule update --init --recursive`?

**Comment by ycollet** [comment]
Hello,

Thanks for the "--recursive --init" options. I finally succeded to get 
the gaccordion repo.

Best regards,

YC


Le 08/10/2017 à 00:10, Taylor Holberton a écrit :
