### ISSUE TITLE
Dead link on the website

### ISSUE THREAD

**Issue by trebmuh** [gnu-guitar/gnu-guitar#3]
Hi,

on that page : http://gnu-guitar.com/recordings.html the link http://gnu-guitar.com/recordings/gnuitar-0.3.3-sample-1.flac is dead because missing a "0" (it should be http://gnu-guitar.com/recordings/gnuitar-0.3.3-sample-01.flac ).

Hope that helps.

**Comment by tay10r** [comment]
Thanks! Fixed it.
