### ISSUE TITLE
Gnu-guitar crashes at loading effect

### ISSUE THREAD

**Issue by sub26nico** [gnu-guitar/gnu-guitar#4]
Hi,
I'm on an Debian Stretch audio-oriented distro , LibraZiK (http://librazik.tuxfamily.org/),
I installed GNUitar-0.3.3-Linux.deb from http://gnu-guitar.com/downloads.html, 
and when I launch it, it's ok, but when I try to load an effect by clicking on it 
(on the right side of the GUI), Gnu-guitar crashes. 
"Segmentation fault". 
I can't say much more. It happens with Jack or Alsa.

**Comment by tay10r** [comment]
Okay, I'll take a look when I get back today.

**Comment by sub26nico** [comment]
I found a solution, before adding an effect, I have to click on 'Cycle Preset' on the left of 
the UI, and It's working, GnuGuitar doen't crash and I can save and load preset. 
But if I 'forgot' to click on 'Cycle Preset', it crashes.

**Comment by tay10r** [comment]
Is there a download available for the distro?

**Comment by sub26nico** [comment]
Yes, here : http://librazik.lamacloud.com/
You can also install Debian Stretch with Mate and add the repos like explains here (in french)
http://librazik.tuxfamily.org/doc2/manuel/installer_librazik/debianstretch

**Comment by tay10r** [comment]
So I ran the image in VirtualBox and wasn't able to reproduce the bug.

Here's an image.

![screenshot from 2018-02-15 19-46-30](https://user-images.githubusercontent.com/4486381/36290182-0f30c9d6-1292-11e8-9086-9b34c65030da.png)

**Comment by sub26nico** [comment]
"Did the segfault occur while the audio was running, or while it was stopped?" 

At the opening of gnuguitar, it happens when audio is running or not running.
But once I loaded preset, it doesn't happen anymore. 
If I launch gnuguitar, before opening a preset (if not loaded), I have to click on 'Cycle preset' 
and I can load effects, with audio running or not running.

I made tests on my laptop with the same distro, and after one crash at the first launch, 
it doesn't happen anymore. I suspect my desktop pc to be the problem.

**Comment by sub26nico** [comment]
I think I found, it is a error 45 (45 cm from the screen), me !
At the opening, the window of gnuguitar is reduced, if I click on 'add' it crash (with no fx selected 
because the reduced windows don't show the fx selection). 
With a full window, the selection of any fx before 'add' doesn't crash anymore.

**Comment by sub26nico** [comment]
Do you want I closed here ?

**Comment by tay10r** [comment]
Yes, if you're no longer getting the problem then you can close the issue. Keep in mind I'm working on v0.4.x, which is very much different from the older version you're running. I will hopefully have a stable release sometime this year.

**Comment by sub26nico** [comment]
Ok, thanks.
